/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
    "./agent/**/*.{ts,tsx,js,jsx}",
  ],
  safelist: [
    // Ensure workflow icon colors are never purged
    "bg-slate-100",
    "text-slate-600",
    "bg-gray-100",
    "text-gray-600",
    "bg-zinc-100",
    "text-zinc-600",
    "bg-neutral-100",
    "text-neutral-600",
    "bg-stone-100",
    "text-stone-600",
    "bg-red-100",
    "text-red-600",
    "bg-orange-100",
    "text-orange-600",
    "bg-amber-100",
    "text-amber-600",
    "bg-yellow-100",
    "text-yellow-600",
    "bg-lime-100",
    "text-lime-600",
    "bg-green-100",
    "text-green-600",
    "bg-emerald-100",
    "text-emerald-600",
    "bg-teal-100",
    "text-teal-600",
    "bg-cyan-100",
    "text-cyan-600",
    "bg-sky-100",
    "text-sky-600",
    "bg-blue-100",
    "text-blue-600",
    "bg-indigo-100",
    "text-indigo-600",
    "bg-violet-100",
    "text-violet-600",
    "bg-purple-100",
    "text-purple-600",
    "bg-fuchsia-100",
    "text-fuchsia-600",
    "bg-pink-100",
    "text-pink-600",
    "bg-rose-100",
    "text-rose-600",
  ],
  theme: {
    extend: {
      fontFamily: {
        "comic-mono": ['"Comic Mono"', "ui-monospace", "monospace"],
        inter: ["var(--font-inter)", "sans-serif"],
        serif: ["var(--font-source-serif-pro)", "Georgia", "serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      components: {
        ".scrollbar-pretty":
          "overflow-y-scroll [&::-webkit-scrollbar]:w-1.5 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-gray-300 [&::-webkit-scrollbar-track]:bg-transparent",
      },
      colors: {
        // Sustainability palette
        "forest-green": "var(--forest-green)",
        "charcoal-teal": "var(--charcoal-teal)",
        stone: "var(--stone)",
        sand: "var(--sand)",
        clay: "var(--clay)",
        sage: "var(--sage)",
        copper: "var(--copper)",
        amber: "var(--amber)",
        "ocean-blue": "var(--ocean-blue)",
        "almost-black": "var(--almost-black)",
        "off-white": "var(--off-white)",
        // Category colors
        "governance-blue": "var(--governance-blue)",
        "impact-terra": "var(--impact-terra)",
        "innovation-mint": "var(--innovation-mint)",
        "standards-gold": "var(--standards-gold)",
        "engagement-charcoal": "var(--engagement-charcoal)",
        "strategy-mauve": "var(--strategy-mauve)",
        // Semantic colors
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        "input-background": "var(--input-background)",
        ring: "var(--ring)",
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
        },
        // Sidebar colors
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("tailwind-scrollbar")],
};
